In [1]:
import pandas as pd

In [2]:
data = {
    "First name" : ["Bhavika" , "Chaitanya" , "Dharya"],
    "Last name" : ["Chopra" , "Garg" , "Chopra"],
    "Email" : ["bhavikachopra@gmail.com" , "chaitanyagarg@gmail.com", "dharyachopra@gmail.com"]
}

In [4]:
df = pd.DataFrame(data)
df

  First name Last name                    Email
0    Bhavika    Chopra  bhavikachopra@gmail.com
1  Chaitanya      Garg  chaitanyagarg@gmail.com
2     Dharya    Chopra   dharyachopra@gmail.com

In [5]:
#changing index to email
df.set_index('Email' , inplace=True)

In [6]:
df

                        First name Last name
Email
bhavikachopra@gmail.com    Bhavika    Chopra
chaitanyagarg@gmail.com  Chaitanya      Garg
dharyachopra@gmail.com      Dharya    Chopra

In [8]:
#accessing through indexes
df.loc['bhavikachopra@gmail.com']

First name    Bhavika
Last name      Chopra
Name: bhavikachopra@gmail.com, dtype: str

In [9]:
df.reset_index(inplace = True)

In [10]:
df

                     Email First name Last name
0  bhavikachopra@gmail.com    Bhavika    Chopra
1  chaitanyagarg@gmail.com  Chaitanya      Garg
2   dharyachopra@gmail.com     Dharya    Chopra