In [1]:
import pandas as pd

In [2]:
data = {
    "First name": ["Bhavika", "Chaitanya", "Dharya"],
    "Last name": ["Chopra", "Garg", "Chopra"],
    "Email": ["bhavikachopra@gmail.com", "chaitanyagarg@gmail.com", "dharyachopra@gmail.com"]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  First name Last name                    Email
0    Bhavika    Chopra  bhavikachopra@gmail.com
1  Chaitanya      Garg  chaitanyagarg@gmail.com
2     Dharya    Chopra   dharyachopra@gmail.com

In [7]:
#filtering using loc
filt = df['Last name'] == 'Chopra'

In [8]:
df.loc[filt]

  First name Last name                    Email
0    Bhavika    Chopra  bhavikachopra@gmail.com
2     Dharya    Chopra   dharyachopra@gmail.com

In [9]:
#accesing columns using the same filter
df.loc[filt , 'Email']

0    bhavikachopra@gmail.com
2     dharyachopra@gmail.com
Name: Email, dtype: str

In [15]:
#using & | ~
filt2 = (df['First name'] == 'Bhavika') & (df['Last name'] == 'Chopra')

In [14]:
df.loc[filt2]

  First name Last name                    Email
0    Bhavika    Chopra  bhavikachopra@gmail.com

In [16]:
filt3 = (df['First name'] == 'Bhavika') | (df['Last name'] == 'Chopra')

In [17]:
df.loc[filt3]

  First name Last name                    Email
0    Bhavika    Chopra  bhavikachopra@gmail.com
2     Dharya    Chopra   dharyachopra@gmail.com

In [18]:
df.loc[~filt3]

  First name Last name                    Email
1  Chaitanya      Garg  chaitanyagarg@gmail.com